# Generated by Django 5.0.6 on 2024-08-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_username_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
