# Generated by Django 5.0.6 on 2024-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_remove_blog_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=170, null=True, verbose_name='транслит (слаг)')),
                ('content', models.TextField(verbose_name='содержимое заметки')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='notes/', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('count_view', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
