# Generated by Django 5.0.6 on 2024-07-26 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_remove_blog_preview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('pk',), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_img',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views_count',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, help_text='Введите содержимое', max_length=100, verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='blog',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/photo', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=100, verbose_name='Название'),
        ),
    ]
