# Generated by Django 5.0.6 on 2024-06-22 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'category', 'created_at', 'updated_ad'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания (записи в БД)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Изображение (превью)'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_ad',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего изменения (записи в БД)'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_counter',
            field=models.PositiveIntegerField(default=0, help_text='Количество просмотров данного товара', verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена за покупку'),
        ),
    ]
